### ISSUE TITLE
Problemas al usar pip install pipenv en el servidor

### ISSUE THREAD

**Issue by arpincheira** [IIC2413/Syllabus-2019-1#121]
Hola buenas, se que puede que no sea lo mejor pero con mi grupo estábamos tratando de usar  un archivo de Python en el servidor que acceda a nuestra base de datos en psql y con eso transformar la tabla de usuarios actual(con todos los usuarios creados hasta el momento en la página y no solo los default) a un archivo json. El problema es que para esto necesitamos instalar los paquetes que queremos utilizar por medio de pipenv pero al instalar esto en el servidor aparece el siguiente error:

`Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pipenv-2018.11.26.dist-info'

Storing debug log for failure in /home/grupo41/.pip/pip.log
` 
Lo he buscado y a priori no me aparece la solución del error, la duda es:
¿ debemos como grupo simplemente buscar otro método o si es que es importante que esto funcione y el error es algo anormal?

**Comment by alanezz** [comment]
Hola,

No tienen los permisos para hacer instalaciones. Lo mejor es que si lo necesitan trabajen con los csv en su computador. Otra opción es hacer export en psql de su tabla a un csv y trabajar con aquel documento.

Saludos.
